//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knkV1.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("knkV1.Lang.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Anulo {
            get {
                return ResourceManager.GetString("Anulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atach:.
        /// </summary>
        internal static string Bashko {
            get {
                return ResourceManager.GetString("Bashko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string btnGjuha {
            get {
                return ResourceManager.GetString("btnGjuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string btnKontakt {
            get {
                return ResourceManager.GetString("btnKontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string btnLog {
            get {
                return ResourceManager.GetString("btnLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string btnNdihma {
            get {
                return ResourceManager.GetString("btnNdihma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string btnRrethNesh {
            get {
                return ResourceManager.GetString("btnRrethNesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ADM.
        /// </summary>
        internal static string btnShtoAdmin {
            get {
                return ResourceManager.GetString("btnShtoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Datelindja {
            get {
                return ResourceManager.GetString("Datelindja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Emri {
            get {
                return ResourceManager.GetString("Emri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Femer {
            get {
                return ResourceManager.GetString("Femer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter  by municipalities.
        /// </summary>
        internal static string FiltroSipasKomunes {
            get {
                return ResourceManager.GetString("FiltroSipasKomunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by possition.
        /// </summary>
        internal static string FiltroSipasPozites {
            get {
                return ResourceManager.GetString("FiltroSipasPozites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by street.
        /// </summary>
        internal static string FiltroSipasRruges {
            get {
                return ResourceManager.GetString("FiltroSipasRruges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by street nr.
        /// </summary>
        internal static string FiltroSipasVendbanimi {
            get {
                return ResourceManager.GetString("FiltroSipasVendbanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by place.
        /// </summary>
        internal static string FiltroSipasVendit {
            get {
                return ResourceManager.GetString("FiltroSipasVendit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Menagment System.
        /// </summary>
        internal static string frmMenaxhoAdresat {
            get {
                return ResourceManager.GetString("frmMenaxhoAdresat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gjinia {
            get {
                return ResourceManager.GetString("Gjinia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        internal static string Komuna {
            get {
                return ResourceManager.GetString("Komuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Konfirmo {
            get {
                return ResourceManager.GetString("Konfirmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string kthehu {
            get {
                return ResourceManager.GetString("kthehu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblFshij {
            get {
                return ResourceManager.GetString("lblFshij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacion for sending Email from API C#.
        /// </summary>
        internal static string lblInfopersonale {
            get {
                return ResourceManager.GetString("lblInfopersonale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string lblKerko {
            get {
                return ResourceManager.GetString("lblKerko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string lblModifiko {
            get {
                return ResourceManager.GetString("lblModifiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string lblRegjistro {
            get {
                return ResourceManager.GetString("lblRegjistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string llRegjistrohu {
            get {
                return ResourceManager.GetString("llRegjistrohu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Mashkull {
            get {
                return ResourceManager.GetString("Mashkull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Mbiemri {
            get {
                return ResourceManager.GetString("Mbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string Mesazhi {
            get {
                return ResourceManager.GetString("Mesazhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify address.
        /// </summary>
        internal static string ModifikoAdresen {
            get {
                return ResourceManager.GetString("ModifikoAdresen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string Nga {
            get {
                return ResourceManager.GetString("Nga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street nr.
        /// </summary>
        internal static string nrVend {
            get {
                return ResourceManager.GetString("nrVend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string Paraqit {
            get {
                return ResourceManager.GetString("Paraqit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Pastro {
            get {
                return ResourceManager.GetString("Pastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Profesioni {
            get {
                return ResourceManager.GetString("Profesioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Rruga {
            get {
                return ResourceManager.GetString("Rruga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string Shtegu {
            get {
                return ResourceManager.GetString("Shtegu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Shteti {
            get {
                return ResourceManager.GetString("Shteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarifications.
        /// </summary>
        internal static string sqarime {
            get {
                return ResourceManager.GetString("sqarime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string Subjekt {
            get {
                return ResourceManager.GetString("Subjekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string tlsMbyll {
            get {
                return ResourceManager.GetString("tlsMbyll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background.
        /// </summary>
        internal static string tsdndryshoPrapavijen {
            get {
                return ResourceManager.GetString("tsdndryshoPrapavijen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string tsdOpsione {
            get {
                return ResourceManager.GetString("tsdOpsione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string tstAnglisht {
            get {
                return ResourceManager.GetString("tstAnglisht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string tstGjuha {
            get {
                return ResourceManager.GetString("tstGjuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string tstInfo {
            get {
                return ResourceManager.GetString("tstInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time:.
        /// </summary>
        internal static string tstKohaAktuale {
            get {
                return ResourceManager.GetString("tstKohaAktuale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tstNdihma {
            get {
                return ResourceManager.GetString("tstNdihma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string tstNdihma_Kontakto {
            get {
                return ResourceManager.GetString("tstNdihma_Kontakto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tstNdihma_Ndihma {
            get {
                return ResourceManager.GetString("tstNdihma_Ndihma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string tstNdihma_Rrethnesh {
            get {
                return ResourceManager.GetString("tstNdihma_Rrethnesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        internal static string tstShqip {
            get {
                return ResourceManager.GetString("tstShqip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string tstStatistika {
            get {
                return ResourceManager.GetString("tstStatistika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Vendi {
            get {
                return ResourceManager.GetString("Vendi", resourceCulture);
            }
        }
    }
}
